export const text = {
  APP_NAME: 'سیستم جامع مدیریت وظایف',
  APP_SHORT_NAME: 'مدیریت وظایف',
  SAVE: 'ذخیره',
  CANCEL: 'انصراف',
  CONFIRM: 'تأیید',
  DELETE: 'حذف',
  EDIT: 'ویرایش',
  BACK: 'بازگشت',
  BACK_TO_LIST: 'بازگشت به لیست',
  RETRY: 'تلاش مجدد',
  ALL: 'همه',
  ITEMS_COUNT_SUFFIX: 'مورد',
  REQUIRED_EM: 'این فیلد الزامی است.',
  ONLY_NUMBERS_EM: 'این فیلد باید شامل اعداد باشد.',
  MIN_PRICE_EM: 'مبلغ وارد شده کمتر از حد مجاز است.',
  TITLE_MIN_EM: 'عنوان باید حداقل ۵ کاراکتر باشد.',
  TITLE_MAX_EM: 'عنوان نباید بیشتر از ۱۲۰ کاراکتر باشد.',
  DESCRIPTION_MIN_EM: 'توضیحات باید حداقل ۱۰ کاراکتر باشد.',
  DESCRIPTION_MAX_EM: 'توضیحات نباید بیشتر از ۲۰۰۰ کاراکتر باشد.',
  STATUS_REQUIRED_EM: 'وضعیت را انتخاب کنید.',
  PRIORITY_REQUIRED_EM: 'اولویت را انتخاب کنید.',
  ASSIGNEE_MIN_EM: 'نام مسئول باید حداقل ۲ کاراکتر باشد.',
  ASSIGNEE_MAX_EM: 'نام مسئول نباید بیشتر از ۶۰ کاراکتر باشد.',
  DUE_DATE_REQUIRED_EM: 'تاریخ سررسید الزامی است.',
  DUE_DATE_INVALID_EM: 'تاریخ سررسید معتبر نیست.',
  STATUS_OPEN: 'باز',
  STATUS_IN_PROGRESS: 'در حال انجام',
  STATUS_DONE: 'انجام‌شده',
  PRIORITY_LOW: 'کم',
  PRIORITY_MEDIUM: 'متوسط',
  PRIORITY_HIGH: 'بالا',
  PRIORITY_CRITICAL: 'بحرانی',
  NEW_TASK: 'وظیفه جدید',
  TASK_LIST_TITLE: 'لیست وظایف',
  SEARCH_PLACEHOLDER: 'جستجو در عنوان و توضیحات…',
  FILTER_STATUS: 'وضعیت',
  FILTER_PRIORITY: 'اولویت',
  FILTER_ASSIGNEE: 'مسئول',
  SORT_LABEL: 'مرتب‌سازی',
  SORT_NEWEST_CREATED: 'جدیدترین ایجاد',
  SORT_OLDEST_CREATED: 'قدیمی‌ترین ایجاد',
  SORT_DUE_SOON: 'نزدیک‌ترین سررسید',
  SORT_DUE_LATE: 'دورترین سررسید',
  CLEAR_FILTERS: 'پاک‌کردن فیلترها',
  LOADING_TASKS: 'در حال دریافت وظایف…',
  NO_RESULTS_TITLE: 'نتیجه‌ای یافت نشد',
  NO_RESULTS_DESCRIPTION: 'فیلترها را تغییر دهید یا پاک کنید تا نتایج بیشتری ببینید.',
  NO_TASKS_TITLE: 'هنوز وظیفه‌ای ثبت نشده',
  NO_TASKS_DESCRIPTION: 'برای شروع، اولین وظیفه را ایجاد کنید.',
  DELETE_TASK_TITLE: 'حذف وظیفه',
  DELETE_TASK_CONFIRM_TEMPLATE: (title: string) => `آیا از حذف «${title}» مطمئن هستید؟ این عملیات قابل بازگشت نیست.`,
  TASK_DELETED_TOAST: (title: string) => `وظیفه «${title}» حذف شد.`,
  TASK_DELETE_FAILED_TOAST: 'حذف وظیفه با خطا مواجه شد.',
  COLUMN_ID: 'شناسه',
  COLUMN_TITLE: 'عنوان',
  COLUMN_STATUS: 'وضعیت',
  COLUMN_PRIORITY: 'اولویت',
  COLUMN_ASSIGNEE: 'مسئول',
  COLUMN_DUE_DATE: 'تاریخ سررسید',
  COLUMN_CREATED_AT: 'تاریخ ایجاد',
  COLUMN_ACTIONS: 'عملیات',
  INVALID_TASK_ID: 'شناسه وظیفه نامعتبر است.',
  LOADING_TASK: 'در حال بارگذاری وظیفه…',
  TASK_NOT_FOUND: 'این وظیفه یافت نشد.',
  DESCRIPTION_LABEL: 'توضیحات',
  ASSIGNEE_LABEL: 'مسئول',
  DUE_DATE_LABEL: 'تاریخ سررسید',
  CREATED_AT_LABEL: 'تاریخ ایجاد',
  CREATE_TASK_TITLE: 'ایجاد وظیفه جدید',
  EDIT_TASK_TITLE: 'ویرایش وظیفه',
  CREATE_TASK_SUBMIT: 'ایجاد وظیفه',
  SAVE_CHANGES: 'ذخیره تغییرات',
  TASK_CREATED_TOAST: (title: string) => `وظیفه «${title}» ایجاد شد.`,
  TASK_CREATE_FAILED_TOAST: 'ایجاد وظیفه با خطا مواجه شد.',
  TASK_UPDATED_TOAST: (title: string) => `وظیفه «${title}» ویرایش شد.`,
  TASK_UPDATE_FAILED_TOAST: 'ویرایش وظیفه با خطا مواجه شد.',
  FIELD_TITLE: 'عنوان',
  FIELD_DESCRIPTION: 'توضیحات',
  FIELD_STATUS: 'وضعیت',
  FIELD_PRIORITY: 'اولویت',
  FIELD_DUE_DATE: 'تاریخ سررسید',
  FIELD_ASSIGNEE: 'مسئول',
  NOT_FOUND_CODE: '۴۰۴',
  NOT_FOUND_MESSAGE: 'صفحه‌ای که دنبالش بودید پیدا نشد.',
  NOT_FOUND_ACTION: 'بازگشت به لیست وظایف',
  GENERIC_LOADING: 'در حال بارگذاری…',
  GENERIC_EMPTY_TITLE: 'موردی یافت نشد',
  GENERIC_EMPTY_DESCRIPTION: 'هیچ وظیفه‌ای با این مشخصات ثبت نشده است.',
  GENERIC_ERROR_TITLE: 'مشکلی پیش آمد',
  GENERIC_ERROR_MESSAGE: 'مشکلی در ارتباط با سرور پیش آمد.',
  UNEXPECTED_ERROR: 'خطایی غیرمنتظره رخ داد.',
  DATE_PICKER_TODAY: 'امروز',
  DATE_PICKER_NEXT_MONTH: 'ماه بعد',
  DATE_PICKER_PREV_MONTH: 'ماه قبل',
} as const;
