const text = {
    APP_NAME: "سیستم جامع مدیریت وظایف",
    REQUIRED_EM: "این فیلد الزامی است.",
    TITLE_MIN_EM: "عنوان باید حداقل ۵ کاراکتر باشد.",
    DESCRIPTION_MIN_EM: "توضیحات باید حداقل ۱۰ کاراکتر باشد.",
    ASSIGNEE_MIN_EM: "نام مسئول باید حداقل ۲ کاراکتر باشد.",
    EMPTY_TASKS: "وظیفه‌ای یافت نشد.",
    FETCH_ERROR: "خطا در دریافت اطلاعات.",
    CREATE_SUCCESS: "وظیفه با موفقیت ثبت شد.",
    UPDATE_SUCCESS: "وظیفه با موفقیت ویرایش شد.",
    DELETE_SUCCESS: "وظیفه با موفقیت حذف شد.",
    DELETE_CONFIRM: "آیا از حذف این وظیفه مطمئن هستید؟",
    BACK_TO_LIST: "بازگشت به لیست وظایف",
    CREATE_TASK: "ایجاد وظیفه",
    EDIT_TASK: "ویرایش وظیفه",
    TASK_LIST: "لیست وظایف",
    TASK_DETAILS: "جزئیات وظیفه",
    ARE_YOU_SURE: "آیا مطمئن هستید؟",
    CANCEL: "انصراف",
    DELETE: "حذف",
    ITEM_NOT_FOUND: "موردی یافت نشد",
    ERROR_IS_HAPPEN: "خطایی رخ داده است",
    TITLE: "عنوان",
    DESCRIPTION: "توضیحات",
    ASSIGNEE: "مسئول",
    STATUS: "وضعیت",
    OPEN: "باز",
    CLOSED: "بسته",
    PRIORITY: "اولویت",
    LOW: "کم",
    MEDIUM: "متوسط",
    HIGH: "زیاد",
    SUBMIT: "ثبت",
    ID: "شناسه",
    DUE_DATE: "تاریخ سررسید",
    CREATED_AT: "تاریخ ایجاد",
    DELETE_TASK: "حذف وظیفه",
    PAGE_NOT_FOUND: "صفحه پیدا نشد",
}



export default text;